# Ba Configuration File

# The UID of the account the owns the bot.
# 
# This is used to make sure only the bot owner
# can run certian commands
bot_owner: 145696462959935488

# Prefix for all bot commands.
# 
# Prefix has a trailing space so commands can
# be run as `?ba help` instead of `?bahelp`
#
# DEFAULT: 'ba? '
command_prefix: '?ba '

# The default permissions for the bot.
#
# DEFAULT: 2112
permissions: 2112